// Code generated by MockGen. DO NOT EDIT.
// Source: album_catalog.go

// Package album_catalog is a generated GoMock package.
package album_catalog

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAlbumCatalog is a mock of AlbumCatalog interface.
type MockAlbumCatalog struct {
	ctrl     *gomock.Controller
	recorder *MockAlbumCatalogMockRecorder
}

// MockAlbumCatalogMockRecorder is the mock recorder for MockAlbumCatalog.
type MockAlbumCatalogMockRecorder struct {
	mock *MockAlbumCatalog
}

// NewMockAlbumCatalog creates a new mock instance.
func NewMockAlbumCatalog(ctrl *gomock.Controller) *MockAlbumCatalog {
	mock := &MockAlbumCatalog{ctrl: ctrl}
	mock.recorder = &MockAlbumCatalogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlbumCatalog) EXPECT() *MockAlbumCatalogMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockAlbumCatalog) Generate(folder string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", folder)
	ret0, _ := ret[0].(error)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockAlbumCatalogMockRecorder) Generate(folder interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockAlbumCatalog)(nil).Generate), folder)
}

// GetMapDir mocks base method.
func (m *MockAlbumCatalog) GetMapDir() *map[string]bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMapDir")
	ret0, _ := ret[0].(*map[string]bool)
	return ret0
}

// GetMapDir indicates an expected call of GetMapDir.
func (mr *MockAlbumCatalogMockRecorder) GetMapDir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMapDir", reflect.TypeOf((*MockAlbumCatalog)(nil).GetMapDir))
}

// Update mocks base method.
func (m *MockAlbumCatalog) Update(path string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", path)
}

// Update indicates an expected call of Update.
func (mr *MockAlbumCatalogMockRecorder) Update(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAlbumCatalog)(nil).Update), path)
}
