services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
      args:
        VITE_API_BASE_URL: "http://localhost:8099"
    container_name: bndcmp_downloader_ui
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: bndcmp_downloader_api
    ports:
      - "8099:8099"
    env_file:
      - ./backend/.env
    volumes:
      - bndcmp_downloader_volume:/app/downloads

volumes:
  bndcmp_downloader_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/jose/Descargas/bndcmp_downloader
      o: bind

